name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Enable and configure Pages for this repo (this fixes your error)
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true   # <— important

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12'   # Vite requires >=20.19 or >=22.12
          cache: 'npm'

      # Decide the Vite base path:
      # - If repo var VITE_PUBLIC_BASE_PATH exists, use it (e.g., "/agsMaranatha/" or "/").
      # - Else default to "/<repo-name>/" which works for project pages.
      - name: Resolve base path
        run: |
          DEFAULT_BASE="/${{ github.event.repository.name }}/"
          if [ -n "${{ vars.VITE_PUBLIC_BASE_PATH }}" ]; then
            echo "VITE_PUBLIC_BASE_PATH=${{ vars.VITE_PUBLIC_BASE_PATH }}" >> "$GITHUB_ENV"
            echo "Using repository variable VITE_PUBLIC_BASE_PATH='${{ vars.VITE_PUBLIC_BASE_PATH }}'"
          else
            echo "VITE_PUBLIC_BASE_PATH=${DEFAULT_BASE}" >> "$GITHUB_ENV"
            echo "No repo var set; defaulting base to '${DEFAULT_BASE}'"
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build site
        env:
          VITE_PUBLIC_BASE_PATH: ${{ env.VITE_PUBLIC_BASE_PATH }}
        run: npm run build

      - name: Upload production-ready site
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
