name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Pages (recommended)
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12'    # Vite requires >=20.19 or >=22.12
          cache: 'npm'

      # Resolve base path:
      # If repo variable VITE_PUBLIC_BASE_PATH is set, use it (e.g. "/agsMaranatha/").
      # Otherwise default to "/<repo-name>/" for project pages.
      - name: Resolve base path
        run: |
          DEFAULT_BASE="/${{ github.event.repository.name }}/"
          # If the repo has a custom domain (CNAME), you likely want "/" instead.
          # You can override via repository variable VITE_PUBLIC_BASE_PATH.
          if [ -n "${{ vars.VITE_PUBLIC_BASE_PATH }}" ]; then
            echo "Using variable VITE_PUBLIC_BASE_PATH='${{ vars.VITE_PUBLIC_BASE_PATH }}'"
            echo "VITE_PUBLIC_BASE_PATH=${{ vars.VITE_PUBLIC_BASE_PATH }}" >> "$GITHUB_ENV"
          else
            echo "No VITE_PUBLIC_BASE_PATH var set; defaulting to ${DEFAULT_BASE}"
            echo "VITE_PUBLIC_BASE_PATH=${DEFAULT_BASE}" >> "$GITHUB_ENV"
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build site
        env:
          VITE_PUBLIC_BASE_PATH: ${{ env.VITE_PUBLIC_BASE_PATH }}
        run: npm run build

      - name: Upload production-ready site
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
